### ISSUE TITLE
Build not working on latest version

### ISSUE THREAD

**Issue by prb28** [mras0/vAmigaSDL#1]
Hi,

I've tried to fix the build https://github.com/prb28/vAmigaSDL/commit/55fa0b9b62023cfc79570dbd36dcdd0b56bdb633
But it crashes when I try to run a program.
My understanding of vamiga is really bad, so I've certainly done something wrong.

Can you help me to find what's wrong ?
thks

**Comment by prb28** [comment]
It works with the stable release and your precedent source file version.
So take your time, I've what I need to look at the gdb protocol.

**Comment by mras0** [comment]
@prb28 I've just updated to latest vAmiga head (2.0b1). I think you'd just need to change `const auto buffer` to `const auto& buffer` to make it work in your version, but easier to just pull latest.

BTW feel free to open more issues, I won't promise anything, but I think I have a reasonable understanding of the code, so I can at least point you in the right direction, and can add some basic support for more things, if you need them. For example folder import (to a virtualized HD) is probably something that could be useful to get it more in line with the *UAE backends.

**Comment by prb28** [comment]
Thanks a lot, I'll try the head, and get back to you for help if needed!

**Comment by dirkwhoffmann** [comment]
> For example folder import (to a virtualized HD) is probably something that could be useful 

Yes, but please keep in mind that this feature hasn't been tested much. So far it has worked in all my own tests, but there is a lot of stuff going on internally when something is written to the file system. There may well be a few corner cases that I have overlooked.

**Comment by mras0** [comment]
> > For example folder import (to a virtualized HD) is probably something that could be useful
> 
> Yes, but please keep in mind that this feature hasn't been tested much. So far it has worked in all my own tests, but there is a lot of stuff going on internally when something is written to the file system. There may well be a few corner cases that I have overlooked.

Only way to find out is to use it :) But yes, I know the feature is very new, and your warning is duly noted, and of course should be passed on to any potential downstream users.

I imagine, though I may be wrong, that most uses of the vscode plugin is people prototyping demos/games, and if they're targeting classic OCS/ECS systems they'll probably have an exe and a small number (maybe a few dozen at most) of assets they load from disk. Though no doubt there will be an enterprising individual with 100000 tiny files and/or keeping every .mod in existence in their hd folder.

**Comment by prb28** [comment]
I like these kind of rocky roads😉.
Don't worry I'm focused on the debugger protocol, I'll use the hard drive option at a certain point but don't worry it's a basic use for me.
And I agree with mras0 about the main use of the extension.

**Comment by prb28** [comment]
@mras0 thanks ! it worked with the head version of vamiga.
